version: 2.1
orbs: 
  ruby: circleci/ruby@1.4.0
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - run: echo "Ruby 2.7 has been installed"
      - run: gem install ffi
      - run: gem uninstall -aIx eventmachine
      - run: gem install eventmachine --platform=ruby
      - run: cd Ruby
      - run: bundle install
